[package]
name = "bench"
version = "1.0.0"
description = "Motoko benchmarking with Mops"
repository = "https://github.com/caffeinelabs/mops-bench"
keywords = [ "bench", "benchmark", "performance", "profiling", "mops" ]
license = "MIT"

[dependencies]
core = "2.0.0"

[toolchain]
moc = "1.0.0"
wasmtime = "40.0.0"

[dev-dependencies]
bench = "1.0.0"
